name: Flutter Windows CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - "test/**"
      - "windows/**"
      - "build/windows/**"

  pull_request:
    branches:
      - master

jobs:
  build_test_and_release_windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          echo "STEAM_API=${{ secrets.API_KEY }}" >> .env
        shell: powershell

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Build Flutter Windows executable
        run: flutter build windows --release

      - name: Zip Windows build for release
        id: zip_build
        run: |
          $buildFolderPath = "build/windows/x64/runner/Release" 
          $outputZipFile = "flutter_windows_app.zip"          
          Set-Location (Join-Path -Path $buildFolderPath -ChildPath "..\..")

          Compress-Archive -Path "runner\Release\*" -DestinationPath $outputZipFile -Force 
          $absoluteZipPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "build/windows/x64/$outputZipFile"

          echo "zip_file=$absoluteZipPath" >> $GITHUB_OUTPUT
        shell: powershell

      - name: Push to Releases (ncipollo/release-action)
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.zip_build.outputs.zip_file }}
          tag: v7.0.${{ github.run_number }}
          name: Release v7.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
