name: Flutter Windows CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - "test/**"
      - "windows/**"
      - "build/windows/**"

  pull_request:
    branches:
      - master

jobs:
  build_and_test_windows:
    runs-on: windows-latest
    outputs:
      zip_path: ${{ steps.zip_build.outputs.zip_file }}

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          echo "STEAM_API=${{ secrets.API_KEY }}" >> .env
        shell: powershell

      # - name: Run Flutter tests
      #   run: flutter test

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Build Flutter Windows executable
        run: flutter build windows --release

      - name: Zip Windows build for release
        id: zip_build
        run: |
          $outputZipFile = "flutter_windows_app.zip"
          # Kompres seluruh isi folder Release ke dalam file ZIP
          Compress-Archive -Path "build/windows/x64/runner/Release/*" -DestinationPath $outputZipFile
          echo "zip_file=$outputZipFile" >> $GITHUB_OUTPUT # Set output path file ZIP
        shell: powershell
      - name: Upload Windows build artifact (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-build-zip
          path: ${{ steps.zip_build.outputs.zip_file }} # Upload file ZIP yang baru dibuat
          retention-days: 5

  create_release:
    needs: build_and_test_windows
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && needs.build_and_test_windows.result == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Windows build artifact (ZIP)
        uses: actions/download-artifact@v4
        with:
          name: flutter-windows-build-zip
          path: ./release-assets

      - name: Get tag version
        id: get_version
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.TAG }}
          name: Release ${{ steps.get_version.outputs.TAG }}
          body: |
            Automatic release of version ${{ steps.get_version.outputs.TAG }}.
            See the changelog for details.
          draft: false
          prerelease: false
          files: ./release-assets/flutter_windows_app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
