name: Flutter Windows CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - "test/**"
      - "windows/**"
      - "build/windows/**"

  pull_request:
    branches:
      - master

jobs:
  build_and_test_windows:
    runs-on: windows-latest
    permissions:
      contents: write
    outputs:
      zip_path: ${{ steps.zip_build.outputs.zip_file }}

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          echo "STEAM_API=${{ secrets.API_KEY }}" >> .env
        shell: powershell

      # - name: Run Flutter tests
      #   run: flutter test

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Build Flutter Windows executable
        run: flutter build windows --release

      - name: Zip Windows build for release
        id: zip_build
        run: |
          $outputZipFile = "flutter_windows_app.zip"
          # Kompres seluruh isi folder Release ke dalam file ZIP
          Compress-Archive -Path "build/windows/x64/runner/Release/*" -DestinationPath $outputZipFile
          echo "zip_file=$outputZipFile" >> $GITHUB_OUTPUT # Set output path file ZIP
        shell: powershell

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.zip_build.outputs.zip_file }}
          tag: v7.0.${{ github.run_number }}
          name: Release v7.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
